### ISSUE TITLE
Text size is relative to diagram width

### ISSUE THREAD

**Issue by allanaaa** [omeka-s-modules/Datavis#19]
With hardcoded font-size and step in the diagram settings, should I be seeing the text change size when the diagram is resized?

<img width="992" alt="Screenshot 2024-01-03 at 12 46 32" src="https://github.com/omeka-s-modules/Datavis/assets/28012148/be8e2a10-6f7a-4707-98e2-d2ace4c8cca4">
<img width="982" alt="Screenshot 2024-01-03 at 12 50 34" src="https://github.com/omeka-s-modules/Datavis/assets/28012148/485627ab-f03f-447c-a9c4-ec7ac17742fd">

We should probably change the interface label and add help text to explain more clearly how things will be rendered. I can't quite figure out why this is happening myself, so maybe you can help me out.

**Comment by jimsafley** [comment]
"Label font size" is the value of the `font-size` attribute of the label. It resolves to pixels, I think. "Space between labels" (step) is used to calculate the total height of the diagram (number of nodes * step). I'm not sure why changing the width of the canvas changes the relative size of the font and step, but that's why I've not included specific measurements. I hope users will see them as a way to fine-tune the space between nodes relative to the overall canvas size.

**Comment by jimsafley** [comment]
After some investigation I've determined that the diagram (including font size) scales to the size of its container via `max-width: 100%`. Otherwise the the diagram would overflow into the surrounding content, which is something to avoid when placed on a page, especially in grid layout.

To make the "Label font size" more user friendly, I've opted for the absolute size keywords (e.g. small, medium, large) over an ambiguous numerical value. I'm not sure how to make the "Space between labels" field any more concrete, but I expect users will intuit its purpose and tweak the number.
