### ISSUE TITLE
Testing: Group by property value for item relationships dataset

### ISSUE THREAD

**Issue by jimsafley** [omeka-s-modules/Datavis#20]
Users can now group by "Property value" when generating an "Item relationships" dataset. The existing "Group by" element now has a "Property value" option that opens a property select menu. After selecting a property and generating the dataset, the resulting diagram will include nodes that are grouped (colored) by unique values of the selected property. For example, choosing `foaf:gender` could group nodes by "male" and "female."

**Comment by allanaaa** [comment]
All of these people have clean "gender" data, but only two of them are reading "male" correctly:

<img width="581" alt="Screenshot 2024-01-04 at 17 55 06" src="https://github.com/omeka-s-modules/Datavis/assets/28012148/e523d6da-d23b-4522-8c6f-d1c4b1d8e9dc">
<img width="607" alt="Screenshot 2024-01-04 at 17 55 10" src="https://github.com/omeka-s-modules/Datavis/assets/28012148/f157bfbe-8016-4843-bac2-7e79de4fe4a2">

None of the blue are reading as "female", just some sort of default group for the rest. Dataset is loading as "null" and "null":
http://6floors.org/workspace/omeka-s/s/bigdata/data-visualization/dataset/12?pretty_print=1

While it's colouring the group it identified, it's not sorting by it when told to:

<img width="898" alt="Screenshot 2024-01-04 at 17 58 58" src="https://github.com/omeka-s-modules/Datavis/assets/28012148/fbb35bb2-6081-44e6-befa-5d28d85d02aa">

**Comment by jimsafley** [comment]
Sorry, I should have mentioned that you need to re-generate the dataset.

**Comment by allanaaa** [comment]
I did, a few times. I can start with a fresh one though.

**Comment by allanaaa** [comment]
Nope, same dataset as the earlier one.

**Comment by jimsafley** [comment]
The most recent commit should work.

**Comment by allanaaa** [comment]
Same thing - it's identifying two people as male, and the rest as "null" (but the grouping is reversed now). 

http://6floors.org/workspace/omeka-s/s/bigdata/data-visualization/diagram/12
http://6floors.org/workspace/omeka-s/s/bigdata/data-visualization/dataset/12?pretty_print=1

**Comment by jimsafley** [comment]
Try the newest changes.

**Comment by allanaaa** [comment]
That's working great now. 

If you choose to group by a linked resource (something like Location, which Sharon has as linked items) then you see an admin/edit link in the popup, rather than the linked item's title.

http://6floors.org/workspace/omeka-s/s/bigdata/data-visualization/diagram/12  

<img width="769" alt="Screenshot 2024-01-08 at 11 57 01" src="https://github.com/omeka-s-modules/Datavis/assets/28012148/fe257d03-b1fe-49f8-b65d-1876d6bc1209">


Also, I wonder if we can include something in the admin interface, like "If you make changes above this line, you will need to re-generate the dataset before you will see an updated visualization." Which would include the search query and the dataset configuration sections. Or we can move the search query to the next section.

**Comment by jimsafley** [comment]
>If you choose to group by a linked resource (something like Location, which Sharon has as linked items) then you see an admin/edit link in the popup, rather than the linked item's title.

I made a change that should fix this.

**Comment by allanaaa** [comment]
Thanks, I'm happy with this!

I will put in the docs that people need to look at the dataset to be sure of what they're seeing, and that hard-refreshing really helps. :)

Just to be sure - when you're grouping, will all the null values always come in the first group? This seems to be the case, but I want to be sure before I put it in the docs.

**Comment by jimsafley** [comment]
Yes, null values will come first, which is usual for database sorting.
